# Generated by Django 3.1.4 on 2020-12-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descrição', models.CharField(max_length=100)),
                ('Quantidade', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
