# Generated by Django 3.1.4 on 2020-12-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_auto_20201208_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Fornecedor',
            field=models.CharField(max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='Preço_unitário',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='Quantidade',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='Total',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
