# Generated by Django 3.1.4 on 2020-12-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_auto_20201208_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Tamanho',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
