# Generated by Django 3.1.4 on 2020-12-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_produto_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Código',
            field=models.DecimalField(decimal_places=4, max_digits=4, null=True),
        ),
    ]
